services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - asadnet
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DB=mysql
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - asadnet
    ports:
      - "5000:5000"
networks:
  asadnet:
